name: avox
description: aVox - Yargılanmadan Dinlen, Anonim Kal.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  cupertino_icons: ^1.0.6
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.7.0
  agora_rtc_engine: ^6.3.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
